sonar.projectKey=ci-api
sonar.projectName=ci-api
sonar.sourceEncoding=UTF-8

# Código que analizaremos
sonar.sources=src
sonar.inclusions=src/**/*.js
sonar.exclusions=node_modules/**,**/*.test.js,**/*.spec.js

# (Opcional) Si luego añades tests y cobertura:
# sonar.tests=src
# sonar.test.inclusions=**/*.test.js,**/*.spec.js
# sonar.javascript.lcov.reportPaths=coverage/lcov.info
